# Editor / AI / Git / Logs
bind -n C-1 select-window -t :1
bind -n C-2 select-window -t :2
bind -n C-3 select-window -t :3
bind -n C-4 select-window -t :4

# Temporary terminal
bind -n C-t display-popup -E -w 80% -h 50%

# Mouse
set -g mouse on

# Modern terminal
set -g default-terminal "tmux-256color"

# Status bar
set -g status-style "bg=#90D7EC,fg=#000000"
